export const resolver = {
    bannerImage: require('../assets/img/banner.jpg'),
    avatar: require('../assets/img/avatar.jpg'),
    arrowLeft: require('../assets/img/arrow-left.png'),
    lottie: require('../assets/animation/lottie.json'),
    android: require('../assets/img/skills/android.png'),
    kotlin: require('../assets/img/skills/kotlin.png'),
    java: require('../assets/img/skills/java.png'),
    rn: require('../assets/img/skills/rn.jpeg'),
    react: require('../assets/img/skills/react.png'),
    css: require('../assets/img/skills/css.png'),
    webpack: require('../assets/img/skills/webpack.png'),
    javascript: require('../assets/img/skills/javascript.png'),
    git: require('../assets/img/skills/git.png'),
    heroku: require('../assets/img/skills/heroku.png'),
    jekyll: require('../assets/img/skills/jekyll.png'),
    html: require('../assets/img/skills/html.png'),
    ruby: require('../assets/img/skills/ruby.png'),
    jenkins: require('../assets/img/skills/jenkins.png')
};
