name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:        
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Use Node.js 8.x
        uses: actions/setup-node@master
        with:
          node-version: 8.x
      
      - name: Install
        run: |
             npm install -g yarn
               
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3-test
        with:
          ACCESS_TOKEN: ${{ secrets.CI_RESUME_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: public
          BUILD_SCRIPT: yarn install && yarn build
