name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:        
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Use Node.js 8.x
        uses: actions/setup-node@master
        with:
          node-version: 8.x
      
      - name: Install
        run: |
             npm install -g yarn

      - name: Build
        run: |
             yarn install && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3-test
        with:
          ACCESS_TOKEN: ${{ secrets.CI_RESUME_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build

      - name : Notification Error
        if: failure()
        env:    
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_USERNAME : "Personal Resume"
            SLACK_AVATAR: repository
        uses: Ilshidur/action-slack@master    
        with:
          args: 'Error deploying :bug:'

      - name : Notification Success
        if: success()
        env:    
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_USERNAME : "Resume"
            SLACK_AVATAR: sender
	    SLACK_CUSTOM_PAYLOAD: '{"text":"Personal Resum has deployed Successfully {{ GITHUB_REPOSITORY }} \\n *with* `new` _line_ escaped","username": "{{ GITHUB_ACTOR }}"}' 	
        uses: Ilshidur/action-slack@master    
        with:
          args: 'Success deploying :rocket:'    
