name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: macos-latest
    env: 
      CI: false 
    steps:        
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: '15'
          architecture: 'x64'
      
      
      - name: Install
        run: |
             npm install -g yarn@v1.22.10

      - name: Build
        run: |
             yarn install && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          ACCESS_TOKEN: ${{ secrets.CI_RESUME_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
        
   
