name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:        
      
      - name: Checkout
        uses: actions/checkout@v1
           
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        env:
          GITHUB_TOKEN: ${{ secrets.CIResumeToken }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: yarn install && yarn build
